//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evius.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evius.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birth date succesfully updated!.
        /// </summary>
        public static string MessageChangeBornDateOk {
            get {
                return ResourceManager.GetString("MessageChangeBornDateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid password confirmation.
        /// </summary>
        public static string MessageChangePasswordNewError {
            get {
                return ResourceManager.GetString("MessageChangePasswordNewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password successfully updated!.
        /// </summary>
        public static string MessageChangePasswordOk {
            get {
                return ResourceManager.GetString("MessageChangePasswordOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong previous password.
        /// </summary>
        public static string MessageChangePasswordOldError {
            get {
                return ResourceManager.GetString("MessageChangePasswordOldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telephone number succesfully updated!.
        /// </summary>
        public static string MessageChangeTelephoneOk {
            get {
                return ResourceManager.GetString("MessageChangeTelephoneOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email already in use.
        /// </summary>
        public static string MessageEmailUsed {
            get {
                return ResourceManager.GetString("MessageEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are now joining this event.
        /// </summary>
        public static string MessageEventAdd {
            get {
                return ResourceManager.GetString("MessageEventAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are no longer joining this event.
        /// </summary>
        public static string MessageEventRemove {
            get {
                return ResourceManager.GetString("MessageEventRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid data.
        /// </summary>
        public static string MessageInvalidData {
            get {
                return ResourceManager.GetString("MessageInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string MessageModifyAnOffertError {
            get {
                return ResourceManager.GetString("MessageModifyAnOffertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string MessageModifyAnOffertSaved {
            get {
                return ResourceManager.GetString("MessageModifyAnOffertSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection settings.
        /// </summary>
        public static string MessageNoData {
            get {
                return ResourceManager.GetString("MessageNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no internet connection available.
        /// </summary>
        public static string MessageNoInternet {
            get {
                return ResourceManager.GetString("MessageNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented..
        /// </summary>
        public static string MessageNoReady {
            get {
                return ResourceManager.GetString("MessageNoReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration was successful!.
        /// </summary>
        public static string MessageRegistrationOK {
            get {
                return ResourceManager.GetString("MessageRegistrationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request added.
        /// </summary>
        public static string MessageRequiredOnOffertAdd {
            get {
                return ResourceManager.GetString("MessageRequiredOnOffertAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request removed.
        /// </summary>
        public static string MessageRequiredOnOffertRemove {
            get {
                return ResourceManager.GetString("MessageRequiredOnOffertRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings disable.
        /// </summary>
        public static string MessageSettingsDisable {
            get {
                return ResourceManager.GetString("MessageSettingsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings enable.
        /// </summary>
        public static string MessageSettingsEnable {
            get {
                return ResourceManager.GetString("MessageSettingsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are now following this user.
        /// </summary>
        public static string MessageUserAdd {
            get {
                return ResourceManager.GetString("MessageUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username used.
        /// </summary>
        public static string MessageUsernameUsed {
            get {
                return ResourceManager.GetString("MessageUsernameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are no longer following this user.
        /// </summary>
        public static string MessageUserRemove {
            get {
                return ResourceManager.GetString("MessageUserRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you change the status of this user.
        /// </summary>
        public static string MessageUserStatusChange {
            get {
                return ResourceManager.GetString("MessageUserStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot change the status of this user.
        /// </summary>
        public static string MessageUserStatusChangeError {
            get {
                return ResourceManager.GetString("MessageUserStatusChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        public static string TextAddEventAddEvent {
            get {
                return ResourceManager.GetString("TextAddEventAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string TextAddEventEmail {
            get {
                return ResourceManager.GetString("TextAddEventEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string TextAddEventPassword {
            get {
                return ResourceManager.GetString("TextAddEventPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string TextAddEventSignIn {
            get {
                return ResourceManager.GetString("TextAddEventSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select source.
        /// </summary>
        public static string TextAddEventWelcome {
            get {
                return ResourceManager.GetString("TextAddEventWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string TextDetailsEventCity {
            get {
                return ResourceManager.GetString("TextDetailsEventCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time:.
        /// </summary>
        public static string TextDetailsEventEndDate {
            get {
                return ResourceManager.GetString("TextDetailsEventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string TextDetailsEventEvent {
            get {
                return ResourceManager.GetString("TextDetailsEventEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string TextDetailsEventEventsFollower {
            get {
                return ResourceManager.GetString("TextDetailsEventEventsFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        public static string TextDetailsEventFollow {
            get {
                return ResourceManager.GetString("TextDetailsEventFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from: .
        /// </summary>
        public static string TextDetailsEventFrom {
            get {
                return ResourceManager.GetString("TextDetailsEventFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info: .
        /// </summary>
        public static string TextDetailsEventInfo {
            get {
                return ResourceManager.GetString("TextDetailsEventInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informations.
        /// </summary>
        public static string TextDetailsEventInformation {
            get {
                return ResourceManager.GetString("TextDetailsEventInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available car seats.
        /// </summary>
        public static string TextDetailsEventLimit {
            get {
                return ResourceManager.GetString("TextDetailsEventLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request ride.
        /// </summary>
        public static string TextDetailsEventMakeRequest {
            get {
                return ResourceManager.GetString("TextDetailsEventMakeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decline.
        /// </summary>
        public static string TextDetailsEventNoFollow {
            get {
                return ResourceManager.GetString("TextDetailsEventNoFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no available rides.
        /// </summary>
        public static string TextDetailsEventNoRequest {
            get {
                return ResourceManager.GetString("TextDetailsEventNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove request.
        /// </summary>
        public static string TextDetailsEventRemoveRequest {
            get {
                return ResourceManager.GetString("TextDetailsEventRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to require a ride.
        /// </summary>
        public static string TextDetailsEventRequired {
            get {
                return ResourceManager.GetString("TextDetailsEventRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string TextDetailsEventSave {
            get {
                return ResourceManager.GetString("TextDetailsEventSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start time:.
        /// </summary>
        public static string TextDetailsEventStartDate {
            get {
                return ResourceManager.GetString("TextDetailsEventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offer a ride.
        /// </summary>
        public static string TextDetailsOffer {
            get {
                return ResourceManager.GetString("TextDetailsOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string TextHomeActivity {
            get {
                return ResourceManager.GetString("TextHomeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + add event.
        /// </summary>
        public static string TextHomeAddEvent {
            get {
                return ResourceManager.GetString("TextHomeAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clans.
        /// </summary>
        public static string TextHomeClan {
            get {
                return ResourceManager.GetString("TextHomeClan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string TextHomeEvents {
            get {
                return ResourceManager.GetString("TextHomeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will join the event.
        /// </summary>
        public static string TextHomeEventsFollowedByUser {
            get {
                return ResourceManager.GetString("TextHomeEventsFollowedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string TextHomeEventsFollower {
            get {
                return ResourceManager.GetString("TextHomeEventsFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your events.
        /// </summary>
        public static string TextHomeEventsWelcome {
            get {
                return ResourceManager.GetString("TextHomeEventsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TextHomeHome {
            get {
                return ResourceManager.GetString("TextHomeHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TextHomeLogout {
            get {
                return ResourceManager.GetString("TextHomeLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string TextHomeMessages {
            get {
                return ResourceManager.GetString("TextHomeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities to display here :(.
        /// </summary>
        public static string TextHomeNoActivity {
            get {
                return ResourceManager.GetString("TextHomeNoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t joined any event, yet..
        /// </summary>
        public static string TextHomeNoEvents {
            get {
                return ResourceManager.GetString("TextHomeNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications to display here :(.
        /// </summary>
        public static string TextHomeNoNotification {
            get {
                return ResourceManager.GetString("TextHomeNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string TextHomeNotification {
            get {
                return ResourceManager.GetString("TextHomeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your notifications.
        /// </summary>
        public static string TextHomeNotificationWelcome {
            get {
                return ResourceManager.GetString("TextHomeNotificationWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TextHomeProfile {
            get {
                return ResourceManager.GetString("TextHomeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string TextHomeReportBug {
            get {
                return ResourceManager.GetString("TextHomeReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TextHomeSettings {
            get {
                return ResourceManager.GetString("TextHomeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travels management.
        /// </summary>
        public static string TextHomeTravelManage {
            get {
                return ResourceManager.GetString("TextHomeTravelManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started following you.
        /// </summary>
        public static string TextHomeUserFollowYou {
            get {
                return ResourceManager.GetString("TextHomeUserFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends&apos; activities.
        /// </summary>
        public static string TextHomeWelcome {
            get {
                return ResourceManager.GetString("TextHomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string TextLoginEmail {
            get {
                return ResourceManager.GetString("TextLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string TextLoginLogin {
            get {
                return ResourceManager.GetString("TextLoginLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string TextLoginPassword {
            get {
                return ResourceManager.GetString("TextLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string TextLoginSignIn {
            get {
                return ResourceManager.GetString("TextLoginSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome to Evius.
        /// </summary>
        public static string TextLoginWelcome {
            get {
                return ResourceManager.GetString("TextLoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TextMainLogin {
            get {
                return ResourceManager.GetString("TextMainLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string TextMainRegistration {
            get {
                return ResourceManager.GetString("TextMainRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmed.
        /// </summary>
        public static string TextManageDriveConfirmed {
            get {
                return ResourceManager.GetString("TextManageDriveConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date: .
        /// </summary>
        public static string TextManageDriveDate {
            get {
                return ResourceManager.GetString("TextManageDriveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rides.
        /// </summary>
        public static string TextManageDriveDrive {
            get {
                return ResourceManager.GetString("TextManageDriveDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event name: .
        /// </summary>
        public static string TextManageDriveEventName {
            get {
                return ResourceManager.GetString("TextManageDriveEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no rides available.
        /// </summary>
        public static string TextManageDriveNoOffered {
            get {
                return ResourceManager.GetString("TextManageDriveNoOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no request.
        /// </summary>
        public static string TextManageDriveNoRequest {
            get {
                return ResourceManager.GetString("TextManageDriveNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove request.
        /// </summary>
        public static string TextManageDriveRemoveRequest {
            get {
                return ResourceManager.GetString("TextManageDriveRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your requests.
        /// </summary>
        public static string TextManageDriveRequestWelcome {
            get {
                return ResourceManager.GetString("TextManageDriveRequestWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status: .
        /// </summary>
        public static string TextManageDriveStatus {
            get {
                return ResourceManager.GetString("TextManageDriveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        public static string TextManageDriveWaiting {
            get {
                return ResourceManager.GetString("TextManageDriveWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your rides.
        /// </summary>
        public static string TextManageDriveWelcome {
            get {
                return ResourceManager.GetString("TextManageDriveWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string TextOfferAccept {
            get {
                return ResourceManager.GetString("TextOfferAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted.
        /// </summary>
        public static string TextOfferAccepted {
            get {
                return ResourceManager.GetString("TextOfferAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no users in this list.
        /// </summary>
        public static string TextOfferNoUser {
            get {
                return ResourceManager.GetString("TextOfferNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rides requests.
        /// </summary>
        public static string TextOfferOffer {
            get {
                return ResourceManager.GetString("TextOfferOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refused.
        /// </summary>
        public static string TextOfferRefujed {
            get {
                return ResourceManager.GetString("TextOfferRefujed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string TextOfferRemove {
            get {
                return ResourceManager.GetString("TextOfferRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send message.
        /// </summary>
        public static string TextOfferSendMessage {
            get {
                return ResourceManager.GetString("TextOfferSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        public static string TextOfferWaiting {
            get {
                return ResourceManager.GetString("TextOfferWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birth date.
        /// </summary>
        public static string TextProfileBornDate {
            get {
                return ResourceManager.GetString("TextProfileBornDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string TextProfileEmail {
            get {
                return ResourceManager.GetString("TextProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string TextProfileEventsFollower {
            get {
                return ResourceManager.GetString("TextProfileEventsFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attented events.
        /// </summary>
        public static string TextProfileEventsWelcome {
            get {
                return ResourceManager.GetString("TextProfileEventsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no events.
        /// </summary>
        public static string TextProfileNoEvents {
            get {
                return ResourceManager.GetString("TextProfileNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TextProfileProfile {
            get {
                return ResourceManager.GetString("TextProfileProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        public static string TextProfileTelephone {
            get {
                return ResourceManager.GetString("TextProfileTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string TextProfileTitle {
            get {
                return ResourceManager.GetString("TextProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string TextProfileUsername {
            get {
                return ResourceManager.GetString("TextProfileUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carried.
        /// </summary>
        public static string TextProfileUsernameTitle1 {
            get {
                return ResourceManager.GetString("TextProfileUsernameTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driver.
        /// </summary>
        public static string TextProfileUsernameTitle2 {
            get {
                return ResourceManager.GetString("TextProfileUsernameTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informations.
        /// </summary>
        public static string TextProfileWelcome {
            get {
                return ResourceManager.GetString("TextProfileWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new account.
        /// </summary>
        public static string TextRegistrationCreate {
            get {
                return ResourceManager.GetString("TextRegistrationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string TextRegistrationEmail {
            get {
                return ResourceManager.GetString("TextRegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat email.
        /// </summary>
        public static string TextRegistrationEmailRepeat {
            get {
                return ResourceManager.GetString("TextRegistrationEmailRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string TextRegistrationPassword {
            get {
                return ResourceManager.GetString("TextRegistrationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string TextRegistrationRegistration {
            get {
                return ResourceManager.GetString("TextRegistrationRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string TextRegistrationUsername {
            get {
                return ResourceManager.GetString("TextRegistrationUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ready to join?.
        /// </summary>
        public static string TextRegistrationWelcome {
            get {
                return ResourceManager.GetString("TextRegistrationWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string TextSettingsAbout {
            get {
                return ResourceManager.GetString("TextSettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced settings.
        /// </summary>
        public static string TextSettingsAdvanceWelcome {
            get {
                return ResourceManager.GetString("TextSettingsAdvanceWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic settings.
        /// </summary>
        public static string TextSettingsBasicWelcome {
            get {
                return ResourceManager.GetString("TextSettingsBasicWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth.
        /// </summary>
        public static string TextSettingsBornDate {
            get {
                return ResourceManager.GetString("TextSettingsBornDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to show your date of birth info in your profile info?.
        /// </summary>
        public static string TextSettingsBornDateInfo {
            get {
                return ResourceManager.GetString("TextSettingsBornDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string TextSettingsChange {
            get {
                return ResourceManager.GetString("TextSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string TextSettingsEmail {
            get {
                return ResourceManager.GetString("TextSettingsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to show your email address in your profile info?.
        /// </summary>
        public static string TextSettingsEmailInfo {
            get {
                return ResourceManager.GetString("TextSettingsEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string TextSettingsNewPassword {
            get {
                return ResourceManager.GetString("TextSettingsNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new phone number.
        /// </summary>
        public static string TextSettingsNewTelephone {
            get {
                return ResourceManager.GetString("TextSettingsNewTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string TextSettingsNotification {
            get {
                return ResourceManager.GetString("TextSettingsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow Evius to send you push notifications?.
        /// </summary>
        public static string TextSettingsNotificationInfo {
            get {
                return ResourceManager.GetString("TextSettingsNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old password.
        /// </summary>
        public static string TextSettingsOldPassword {
            get {
                return ResourceManager.GetString("TextSettingsOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string TextSettingsPassword {
            get {
                return ResourceManager.GetString("TextSettingsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap to change your password.
        /// </summary>
        public static string TextSettingsPasswordInfo {
            get {
                return ResourceManager.GetString("TextSettingsPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string TextSettingsPosition {
            get {
                return ResourceManager.GetString("TextSettingsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow Evius to access your location?.
        /// </summary>
        public static string TextSettingsPositionInfo {
            get {
                return ResourceManager.GetString("TextSettingsPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string TextSettingsPrivacy {
            get {
                return ResourceManager.GetString("TextSettingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat new password.
        /// </summary>
        public static string TextSettingsRepeatNewPassword {
            get {
                return ResourceManager.GetString("TextSettingsRepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TextSettingsSettings {
            get {
                return ResourceManager.GetString("TextSettingsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        public static string TextSettingsTelephone {
            get {
                return ResourceManager.GetString("TextSettingsTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to show your phone number in your profile info?.
        /// </summary>
        public static string TextSettingsTelephoneInfo {
            get {
                return ResourceManager.GetString("TextSettingsTelephoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TextSettingsTerms {
            get {
                return ResourceManager.GetString("TextSettingsTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string TextSettingsUsername {
            get {
                return ResourceManager.GetString("TextSettingsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user informations.
        /// </summary>
        public static string TextSettingsWelcome {
            get {
                return ResourceManager.GetString("TextSettingsWelcome", resourceCulture);
            }
        }
    }
}
